// src/content/compatibility/beginnerTrackCompatibility.ts
import type { ContentPack } from '../types';
import type { ValidationIssue } from '../validate';
import { BEGINNER_GROUPS } from '../../tracks/beginnerTrack';

import { bridgePackToBeginnerTrack } from '../adapters/beginnerTrackAdapter';

type Level = 'error' | 'warn';

const BEGINNER_GROUP_ID_SET = new Set<string>(BEGINNER_GROUPS.map((g) => g.id));

function issue(
  level: Level,
  code:
    | 'BEGINNER_COMPAT_GROUP_UNKNOWN'
    | 'BEGINNER_COMPAT_UNIT_UNKNOWN'
    | 'BEGINNER_COMPAT_PREREQ_UNKNOWN',
  message: string,
  extras?: Omit<ValidationIssue, 'level' | 'code' | 'message'>
): ValidationIssue {
  return { level, code, message, ...extras };
}

/**
 * BeginnerTrack compatibility (V3 bridge strategy)
 * ----------------------------------------------
 * בודקים תאימות לפי מה שה־bridge באמת מייצר עבור המסלול.
 *
 * NOTE (V3):
 * יש Packs שהם "Interest packs" (בחירה להורה) ולא אמורים להיכנס למסלול הלימוד.
 * לכן validatePacksBeginnerCompatibility מסנן רק את ה־packs שברצוננו לגשר למסלול.
 */
export function validatePackBeginnerCompatibility(
  pack: ContentPack
): ValidationIssue[] {
  const issues: ValidationIssue[] = [];

  if (!BEGINNER_GROUP_ID_SET.has(pack.id)) {
    issues.push(
      issue(
        'warn',
        'BEGINNER_COMPAT_GROUP_UNKNOWN',
        `Pack id "${pack.id}" is not a known beginnerTrack GroupId (not bridged yet).`,
        { packId: pack.id, path: `packs[${pack.id}].id` }
      )
    );
    return issues;
  }

  const bridged = bridgePackToBeginnerTrack(pack);
  const BRIDGED_UNIT_ID_SET = new Set<string>(bridged.units.map((u) => u.id));

  for (const u of bridged.units) {
    for (const preId of u.prereqUnitIds) {
      if (!BRIDGED_UNIT_ID_SET.has(preId)) {
        issues.push(
          issue(
            'warn',
            'BEGINNER_COMPAT_PREREQ_UNKNOWN',
            `Bridged unit "${u.id}" prereq "${preId}" is not generated by the bridge for pack "${pack.id}".`,
            { packId: pack.id, unitId: u.id, path: `packs[${pack.id}].groups` }
          )
        );
      }
    }
  }

  return issues;
}

/**
 * V3: validate only packs that are intended to be bridged into the track.
 * Right now: colors only.
 */
const BRIDGED_PACK_IDS = new Set<string>(['colors']);

export function validatePacksBeginnerCompatibility(
  packs: readonly ContentPack[]
): ValidationIssue[] {
  const all: ValidationIssue[] = [];
  for (const p of packs) {
    if (!BRIDGED_PACK_IDS.has(p.id)) continue; // ignore selection/hidden packs
    all.push(...validatePackBeginnerCompatibility(p));
  }
  return all;
}
