// src/content/packs/core/numbersPack.ts
import type { ContentItem, ContentPack } from '../../types';

const items: ContentItem[] = [
  { id: 'one', en: 'one', he: 'אחד',
      heNiqqud: 'אֶחָד',
    visual: { kind: 'text', he: '1' } },
  { id: 'two', en: 'two', he: 'שתיים',
      heNiqqud: 'שְׁתַּיִם',
    visual: { kind: 'text', he: '2' } },
  { id: 'three', en: 'three', he: 'שלוש',
      heNiqqud: 'שָׁלוֹשׁ',
    visual: { kind: 'text', he: '3' } },
  { id: 'four', en: 'four', he: 'ארבע',
      heNiqqud: 'אַרְבַּע',
    visual: { kind: 'text', he: '4' } },
  { id: 'five', en: 'five', he: 'חמש',
      heNiqqud: 'חָמֵשׁ',
    visual: { kind: 'text', he: '5' } },
  { id: 'six', en: 'six', he: 'שש',
      heNiqqud: 'שֵׁשׁ',
    visual: { kind: 'text', he: '6' } },
  { id: 'seven', en: 'seven', he: 'שבע',
      heNiqqud: 'שֶׁבַע',
    visual: { kind: 'text', he: '7' } },
  { id: 'eight', en: 'eight', he: 'שמונה',
      heNiqqud: 'שְׁמוֹנֶה',
    visual: { kind: 'text', he: '8' } },
  { id: 'nine', en: 'nine', he: 'תשע',
      heNiqqud: 'תֵּשַׁע',
    visual: { kind: 'text', he: '9' } },
  { id: 'ten', en: 'ten', he: 'עשר',
      heNiqqud: 'עֶשֶׂר',
    visual: { kind: 'text', he: '10' } },

  {
    id: 'eleven',
    en: 'eleven',
    he: 'אחת עשרה',
      heNiqqud: 'אַחַת עֶשְׂרֵה',
    visual: { kind: 'text', he: '11' },
  },
  {
    id: 'twelve',
    en: 'twelve',
    he: 'שתים עשרה',
      heNiqqud: 'שְׁתֵּים עֶשְׂרֵה',
    visual: { kind: 'text', he: '12' },
  },
  {
    id: 'thirteen',
    en: 'thirteen',
    he: 'שלוש עשרה',
      heNiqqud: 'שְׁלוֹשׁ עֶשְׂרֵה',
    visual: { kind: 'text', he: '13' },
  },
  {
    id: 'fourteen',
    en: 'fourteen',
    he: 'ארבע עשרה',
      heNiqqud: 'אַרְבַּע עֶשְׂרֵה',
    visual: { kind: 'text', he: '14' },
  },
  {
    id: 'fifteen',
    en: 'fifteen',
    he: 'חמש עשרה',
      heNiqqud: 'חֲמֵשׁ עֶשְׂרֵה',
    visual: { kind: 'text', he: '15' },
  },
  {
    id: 'sixteen',
    en: 'sixteen',
    he: 'שש עשרה',
      heNiqqud: 'שֵׁשׁ עֶשְׂרֵה',
    visual: { kind: 'text', he: '16' },
  },
  {
    id: 'seventeen',
    en: 'seventeen',
    he: 'שבע עשרה',
      heNiqqud: 'שֶׁבַע עֶשְׂרֵה',
    visual: { kind: 'text', he: '17' },
  },
  {
    id: 'eighteen',
    en: 'eighteen',
    he: 'שמונה עשרה',
      heNiqqud: 'שְׁמוֹנֶה עֶשְׂרֵה',
    visual: { kind: 'text', he: '18' },
  },
  {
    id: 'nineteen',
    en: 'nineteen',
    he: 'תשע עשרה',
      heNiqqud: 'תֵּשַׁע עֶשְׂרֵה',
    visual: { kind: 'text', he: '19' },
  },
  {
    id: 'twenty',
    en: 'twenty',
    he: 'עשרים',
      heNiqqud: 'עֶשְׂרִים',
    visual: { kind: 'text', he: '20' },
  },

  {
    id: 'twenty_one',
    en: 'twenty-one',
    he: 'עשרים ואחת',
      heNiqqud: 'עֶשְׂרִים וְאַחַת',
    visual: { kind: 'text', he: '21' },
  },
  {
    id: 'twenty_two',
    en: 'twenty-two',
    he: 'עשרים ושתיים',
      heNiqqud: 'עֶשְׂרִים וּשְׁתַּיִם',
    visual: { kind: 'text', he: '22' },
  },
  {
    id: 'twenty_three',
    en: 'twenty-three',
    he: 'עשרים ושלוש',
      heNiqqud: 'עֶשְׂרִים וְשָׁלוֹשׁ',
    visual: { kind: 'text', he: '23' },
  },
  {
    id: 'twenty_four',
    en: 'twenty-four',
    he: 'עשרים וארבע',
      heNiqqud: 'עֶשְׂרִים וְאַרְבַּע',
    visual: { kind: 'text', he: '24' },
  },
  {
    id: 'twenty_five',
    en: 'twenty-five',
    he: 'עשרים וחמש',
      heNiqqud: 'עֶשְׂרִים וְחָמֵשׁ',
    visual: { kind: 'text', he: '25' },
  },
  {
    id: 'twenty_six',
    en: 'twenty-six',
    he: 'עשרים ושש',
      heNiqqud: 'עֶשְׂרִים וְשֵׁשׁ',
    visual: { kind: 'text', he: '26' },
  },
  {
    id: 'twenty_seven',
    en: 'twenty-seven',
    he: 'עשרים ושבע',
      heNiqqud: 'עֶשְׂרִים וְשֶׁבַע',
    visual: { kind: 'text', he: '27' },
  },
  {
    id: 'twenty_eight',
    en: 'twenty-eight',
    he: 'עשרים ושמונה',
      heNiqqud: 'עֶשְׂרִים וּשְׁמוֹנֶה',
    visual: { kind: 'text', he: '28' },
  },
  {
    id: 'twenty_nine',
    en: 'twenty-nine',
    he: 'עשרים ותשע',
      heNiqqud: 'עֶשְׂרִים וְתֵּשַׁע',
    visual: { kind: 'text', he: '29' },
  },
  {
    id: 'thirty',
    en: 'thirty',
    he: 'שלושים',
      heNiqqud: 'שְׁלוֹשִׁים',
    visual: { kind: 'text', he: '30' },
  },

  {
    id: 'forty',
    en: 'forty',
    he: 'ארבעים',
      heNiqqud: 'אַרְבָּעִים',
    visual: { kind: 'text', he: '40' },
  },
  {
    id: 'fifty',
    en: 'fifty',
    he: 'חמישים',
      heNiqqud: 'חֲמִשִּׁים',
    visual: { kind: 'text', he: '50' },
  },
  { id: 'sixty', en: 'sixty', he: 'שישים',
      heNiqqud: 'שִׁשִּׁים',
    visual: { kind: 'text', he: '60' } },
  {
    id: 'seventy',
    en: 'seventy',
    he: 'שבעים',
      heNiqqud: 'שִׁבְעִים',
    visual: { kind: 'text', he: '70' },
  },
  {
    id: 'eighty',
    en: 'eighty',
    he: 'שמונים',
      heNiqqud: 'שְׁמוֹנִים',
    visual: { kind: 'text', he: '80' },
  },
  {
    id: 'ninety',
    en: 'ninety',
    he: 'תשעים',
      heNiqqud: 'תִּשְׁעִים',
    visual: { kind: 'text', he: '90' },
  },

  {
    id: 'one_hundred',
    en: 'one hundred',
    he: 'מאה',
      heNiqqud: 'מֵאָה',
    visual: { kind: 'text', he: '100' },
  },
  {
    id: 'two_hundred',
    en: 'two hundred',
    he: 'מאתיים',
      heNiqqud: 'מָאתַיִם',
    visual: { kind: 'text', he: '200' },
  },
  {
    id: 'three_hundred',
    en: 'three hundred',
    he: 'שלוש מאות',
      heNiqqud: 'שְׁלוֹשׁ מֵאוֹת',
    visual: { kind: 'text', he: '300' },
  },
  {
    id: 'four_hundred',
    en: 'four hundred',
    he: 'ארבע מאות',
      heNiqqud: 'אַרְבַּע מֵאוֹת',
    visual: { kind: 'text', he: '400' },
  },
  {
    id: 'five_hundred',
    en: 'five hundred',
    he: 'חמש מאות',
      heNiqqud: 'חֲמֵשׁ מֵאוֹת',
    visual: { kind: 'text', he: '500' },
  },
  {
    id: 'six_hundred',
    en: 'six hundred',
    he: 'שש מאות',
      heNiqqud: 'שֵׁשׁ מֵאוֹת',
    visual: { kind: 'text', he: '600' },
  },
  {
    id: 'seven_hundred',
    en: 'seven hundred',
    he: 'שבע מאות',
      heNiqqud: 'שֶׁבַע מֵאוֹת',
    visual: { kind: 'text', he: '700' },
  },
  {
    id: 'eight_hundred',
    en: 'eight hundred',
    he: 'שמונה מאות',
      heNiqqud: 'שְׁמוֹנֶה מֵאוֹת',
    visual: { kind: 'text', he: '800' },
  },
  {
    id: 'nine_hundred',
    en: 'nine hundred',
    he: 'תשע מאות',
      heNiqqud: 'תֵּשַׁע מֵאוֹת',
    visual: { kind: 'text', he: '900' },
  },

  {
    id: 'one_thousand',
    en: 'one thousand',
    he: 'אלף',
      heNiqqud: 'אֶלֶף',
    visual: { kind: 'text', he: '1000' },
  },
  {
    id: 'two_thousand',
    en: 'two thousand',
    he: 'אלפיים',
      heNiqqud: 'אַלְפַּיִם',
    visual: { kind: 'text', he: '2000' },
  },
  {
    id: 'three_thousand',
    en: 'three thousand',
    he: 'שלושת אלפים',
      heNiqqud: 'שְׁלוֹשֶׁת אֲלָפִים',
    visual: { kind: 'text', he: '3000' },
  },
  {
    id: 'four_thousand',
    en: 'four thousand',
    he: 'ארבעת אלפים',
      heNiqqud: 'אַרְבַּעַת אֲלָפִים',
    visual: { kind: 'text', he: '4000' },
  },
  {
    id: 'five_thousand',
    en: 'five thousand',
    he: 'חמשת אלפים',
      heNiqqud: 'חֲמֵשֶׁת אֲלָפִים',
    visual: { kind: 'text', he: '5000' },
  },
  {
    id: 'six_thousand',
    en: 'six thousand',
    he: 'ששת אלפים',
      heNiqqud: 'שֵׁשֶׁת אֲלָפִים',
    visual: { kind: 'text', he: '6000' },
  },
  {
    id: 'seven_thousand',
    en: 'seven thousand',
    he: 'שבעת אלפים',
      heNiqqud: 'שִׁבְעַת אֲלָפִים',
    visual: { kind: 'text', he: '7000' },
  },
  {
    id: 'eight_thousand',
    en: 'eight thousand',
    he: 'שמונת אלפים',
      heNiqqud: 'שְׁמוֹנַת אֲלָפִים',
    visual: { kind: 'text', he: '8000' },
  },
  {
    id: 'nine_thousand',
    en: 'nine thousand',
    he: 'תשעת אלפים',
      heNiqqud: 'תִּשְׁעַת אֲלָפִים',
    visual: { kind: 'text', he: '9000' },
  },
];

export const numbersPack: ContentPack = {
  id: 'numbers',
  policy: {
    packType: 'core',
    levelTag: 'A',
    // Moved to Layer 3 (Symbols) – Numbers sit with letters/symbols rather than World Objects.
    minLayer: 3,
    maxLayer: 4,
    tags: ['numbers'],
  },
  meta: { tags: ['core', 'beginnerBridge'] },

  title: 'Numbers',
  titleKey: 'content.pack.numbers.title',

  emoji: '🔢',

  description: 'Learn to say and recognize numbers (sound → symbol).',
  descriptionKey: 'content.pack.numbers.desc',

  items,

  groups: [
    {
      id: 'numbers_1_5',
      title: 'Numbers 1–5',
      titleKey: 'beginner.unit.numbers_1_5.title',
      itemIds: ['one', 'two', 'three', 'four', 'five'],
      policy: { minLayer: 3 },
    },
    {
      id: 'numbers_6_10',
      title: 'Numbers 6–10',
      titleKey: 'beginner.unit.numbers_6_10.title',
      itemIds: ['six', 'seven', 'eight', 'nine', 'ten'],
      policy: { minLayer: 3 },
    },
    {
      id: 'numbers_11_15',
      title: 'Numbers 11–15',
      titleKey: 'beginner.unit.numbers_11_15.title',
      itemIds: ['eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen'],
      policy: { minLayer: 3 },
    },
    {
      id: 'numbers_16_20',
      title: 'Numbers 16–20',
      titleKey: 'beginner.unit.numbers_16_20.title',
      itemIds: ['sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty'],
      policy: { minLayer: 3 },
    },
    {
      id: 'numbers_21_25',
      title: 'Numbers 21–25',
      titleKey: 'beginner.unit.numbers_21_25.title',
      itemIds: [
        'twenty_one',
        'twenty_two',
        'twenty_three',
        'twenty_four',
        'twenty_five',
      ],
      policy: { minLayer: 3 },
    },
    {
      id: 'numbers_26_30',
      title: 'Numbers 26–30',
      titleKey: 'beginner.unit.numbers_26_30.title',
      itemIds: [
        'twenty_six',
        'twenty_seven',
        'twenty_eight',
        'twenty_nine',
        'thirty',
      ],
      policy: { minLayer: 3 },
    },

    // ✅ Tens split (V10)
    {
      id: 'tens_10_50',
      title: 'Tens (10–50)',
      titleKey: 'beginner.unit.tens_10_50.title',
      itemIds: ['ten', 'twenty', 'thirty', 'forty', 'fifty'],
      policy: { minLayer: 3 },
    },
    {
      id: 'tens_60_90',
      title: 'Tens (60–90)',
      titleKey: 'beginner.unit.tens_60_90.title',
      itemIds: ['sixty', 'seventy', 'eighty', 'ninety'],
      policy: { minLayer: 3 },
    },

    {
      id: 'hundreds_100_900',
      title: 'Hundreds (100–900)',
      titleKey: 'beginner.unit.hundreds_100_900.title',
      itemIds: [
        'one_hundred',
        'two_hundred',
        'three_hundred',
        'four_hundred',
        'five_hundred',
        'six_hundred',
        'seven_hundred',
        'eight_hundred',
        'nine_hundred',
      ],
      policy: { minLayer: 3 },
    },
    {
      id: 'thousands_1000_9000',
      title: 'Thousands (1000–9000)',
      titleKey: 'beginner.unit.thousands_1000_9000.title',
      itemIds: [
        'one_thousand',
        'two_thousand',
        'three_thousand',
        'four_thousand',
        'five_thousand',
        'six_thousand',
        'seven_thousand',
        'eight_thousand',
        'nine_thousand',
      ],
      policy: { minLayer: 4 },
    },
  ],

  // Track units are bridged from pack.groups into the Beginner track; keep empty to avoid duplication.
  units: [],
};
